from Employee import Employee, SalesEmployee, ManufacturingEmployee

# Common user inputs
name = input("Enter the name of the employee: ")
dept = input("Enter the department of the employee: ")
salary = int(input("Enter the base salary of the employee: "))

# Dynamic user input based on type
employee_type = input("Enter the type of employee (General/Sales/Manufacturing): ").lower()

if employee_type == "sales":  # for sales employee
    no_of_leads = int(input("Enter the number of leads generated by the employee: "))
    sales_emp = SalesEmployee(name, dept, salary, no_of_leads)
    sales_emp.calculate_salary()

elif employee_type == "manufacturing":  # for manufacturing employee
    no_of_extra_hours = int(input("Enter the number of extra hours worked by the employee: "))
    manufacturing_emp = ManufacturingEmployee(name, dept, salary, no_of_extra_hours)
    manufacturing_emp.calculate_salary()

else:  # for general employee
    emp = Employee(name, dept, salary)
    emp.calculate_salary()
